name: Build Electron App

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Executable
        run: npx electron-builder

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Exe
          path: dist/*.exe
